/**
 * Glosarul de termeni.
 *
 * Fiecare intrare are o definiție scurtă (o propoziție, folosită în
 * tooltip) și una extinsă, cu contextul care contează în practică.
 * `termeni` conține variantele sub care apare cuvântul în restul
 * aplicației, ca marcarea automată să le prindă pe toate.
 */
const GLOSAR = [
  {
    id: "dae",
    termen: "DAE",
    termeni: ["DAE", "dobânda anuală efectivă"],
    categorie: "Credite",
    scurt: "Costul total anual al unui credit, incluzând dobânda și comisioanele.",
    lung: "Dobânda anuală efectivă exprimă într-un singur număr tot ce plătești pentru un credit: dobânda propriu-zisă, comisionul de analiză, cel de administrare și asigurările obligatorii. Este singura valoare comparabilă între oferte: două credite cu aceeași dobândă nominală pot avea DAE foarte diferite. Prin lege, băncile sunt obligate să o afișeze.",
    vezi: ["dobanda-nominala", "comision"],
  },
  {
    id: "dobanda-nominala",
    termen: "Dobândă nominală",
    termeni: ["dobândă nominală", "dobânda nominală"],
    categorie: "Credite",
    scurt: "Procentul aplicat sumei împrumutate, fără comisioane.",
    lung: "Este valoarea pe care băncile o afișează cel mai vizibil în reclame, tocmai pentru că este mai mică decât DAE. Nu include niciun comision, deci nu spune cât te costă efectiv creditul. Pentru comparație folosește întotdeauna DAE.",
    vezi: ["dae"],
  },
  {
    id: "anuitate",
    termen: "Anuitate",
    termeni: ["anuitate", "rate egale"],
    categorie: "Credite",
    scurt: "Sistem de rambursare în care rata lunară rămâne constantă.",
    lung: "La un credit cu anuitate, plătești aceeași sumă în fiecare lună, dar compoziția ei se schimbă: la început aproape toată rata este dobândă, iar spre final aproape toată reduce datoria. Alternativa, ratele descrescătoare, începe cu o rată mai mare dar costă mai puțin în total.",
    vezi: ["principal", "amortizare"],
  },
  {
    id: "principal",
    termen: "Principal",
    termeni: ["principal", "soldul creditului"],
    categorie: "Credite",
    scurt: "Suma efectiv împrumutată, care rămâne de rambursat.",
    lung: "Este partea din datorie care nu include dobânda. Doar plățile care reduc principalul îți cresc averea netă, pentru că dobânda este un cost pur. De aceea o plată anticipată făcută devreme economisește mult: reduce principalul cât mai este mult timp de generat dobândă pe el.",
    vezi: ["anuitate", "amortizare"],
  },
  {
    id: "amortizare",
    termen: "Grafic de amortizare",
    termeni: ["amortizare", "grafic de rambursare"],
    categorie: "Credite",
    scurt: "Tabelul care arată, lună cu lună, cât din rată este dobândă și cât principal.",
    lung: "Îl primești obligatoriu la semnarea creditului. Este documentul care face vizibil de ce, după cinci ani de plăți la un credit pe 25 de ani, datoria a scăzut mult mai puțin decât ai plătit.",
    vezi: ["principal", "anuitate"],
  },
  {
    id: "grad-indatorare",
    termen: "Grad de îndatorare",
    termeni: ["grad de îndatorare", "gradul de îndatorare"],
    categorie: "Credite",
    scurt: "Proporția din venitul lunar net care merge către rate.",
    lung: "Băncile din România folosesc de regulă un prag maxim de 40%. Peste acest nivel, o lună fără venit devine imediat o problemă. Se calculează însumând toate ratele lunare, inclusiv creditele de la IFN și cumpărăturile în rate, raportate la venitul net. Pentru creditele în altă monedă decât cea a veniturilor, pragul aplicat este mai mic.",
    vezi: ["biroul-de-credit", "ifn"],
  },
  {
    id: "ifn",
    termen: "IFN",
    termeni: ["IFN", "instituție financiară nebancară", "credit rapid"],
    categorie: "Credite",
    scurt: "Instituție financiară nebancară: dă credite, dar nu are voie să atragă depozite.",
    lung: "IFN-urile acordă creditele rapide, cu acte puține și bani în aceeași zi. Comoditatea se plătește prin dobândă: DAE trece frecvent de 50% pe an, față de 6-7% la un credit ipotecar și 10-14% la unul bancar de nevoi personale. Sunt înregistrate la BNR și raportează la Biroul de Credit ca orice bancă, deci o restanță aici afectează la fel de mult accesul viitor la un credit ipotecar. Înainte de a semna, compară DAE, nu rata lunară: o perioadă mai lungă face rata să pară mică, dar mărește costul total.",
    vezi: ["dae", "grad-indatorare", "avalansa"],
  },
  {
    id: "biroul-de-credit",
    termen: "Biroul de Credit",
    termeni: ["Biroul de Credit"],
    categorie: "Credite",
    scurt: "Baza de date în care băncile raportează istoricul tău de plăți.",
    lung: "Conține informații despre creditele active și despre întârzierile la plată din ultimii patru ani. O întârziere mai mare de 30 de zile rămâne înregistrată și poate duce la refuzul unui credit viitor. Ai dreptul să ceri gratuit, o dată pe an, raportul propriu.",
    vezi: ["grad-indatorare"],
  },

  {
    id: "etf",
    termen: "ETF",
    termeni: ["ETF", "fond index", "fond tranzacționat la bursă"],
    categorie: "Investiții",
    scurt: "Fond care urmărește automat un indice bursier și se tranzacționează ca o acțiune.",
    lung: "Un ETF pe un indice larg cumpără, în proporții fixe, toate companiile din acel indice. Nu încearcă să aleagă câștigătorii, deci are costuri de administrare mult mai mici decât un fond activ, de obicei sub 0,3% pe an față de 1,5-2%. Pe termen lung, această diferență de cost este motivul principal pentru care majoritatea fondurilor active rămân în urma indicelui.",
    vezi: ["diversificare", "comision", "indice"],
  },
  {
    id: "indice",
    termen: "Indice bursier",
    termeni: ["indice bursier", "indice"],
    categorie: "Investiții",
    scurt: "O măsură a evoluției unui grup de companii, folosită ca reper pentru piață.",
    lung: "S&P 500 urmărește 500 de companii mari din SUA, MSCI World urmărește peste 1.500 din țările dezvoltate, BET urmărește cele mai lichide companii de la Bursa de Valori București. Un indice nu poate fi cumpărat direct: cumperi un fond care îl replică.",
    vezi: ["etf", "diversificare"],
  },
  {
    id: "diversificare",
    termen: "Diversificare",
    termeni: ["diversificare", "diversificat"],
    categorie: "Investiții",
    scurt: "Împărțirea investiției între multe active, ca falimentul unuia să nu conteze.",
    lung: "Reduce riscul specific (cel legat de o singură firmă, un sector sau o țară) fără să reducă randamentul așteptat. Este descrisă uneori ca „singurul prânz gratuit din finanțe”. Nu protejează însă împotriva riscului de piață: într-o criză generală scade tot.",
    vezi: ["etf", "volatilitate", "risc-specific"],
  },
  {
    id: "risc-specific",
    termen: "Risc specific",
    termeni: ["risc specific", "risc idiosincratic"],
    categorie: "Investiții",
    scurt: "Riscul legat de o singură companie sau sector, care poate fi eliminat prin diversificare.",
    lung: "Falimentul unei firme, un scandal, pierderea unui contract major. Spre deosebire de riscul de piață, acest tip de risc nu este recompensat: piața nu îți oferă randament suplimentar pentru un risc pe care ai fi putut să-l elimini gratuit, prin diversificare.",
    vezi: ["diversificare", "volatilitate"],
  },
  {
    id: "volatilitate",
    termen: "Volatilitate",
    termeni: ["volatilitate", "volatil"],
    categorie: "Investiții",
    scurt: "Cât de mult oscilează prețul unui activ în timp.",
    lung: "Se măsoară de obicei ca abatere standard anuală a randamentelor. Pentru acțiuni, valorile tipice sunt 15-20% pe an. Volatilitatea nu este același lucru cu riscul de pierdere: pentru cineva care investește pe 20 de ani și nu vinde, oscilația este un inconvenient, nu o pierdere. Devine pierdere doar în momentul vânzării.",
    vezi: ["risc-specific", "diversificare"],
  },
  {
    id: "randament-real",
    termen: "Randament real",
    termeni: ["randament real", "randamentul real"],
    categorie: "Investiții",
    scurt: "Randamentul rămas după scăderea inflației.",
    lung: "Un depozit cu 6% dobândă într-un an cu 8% inflație are un randament real de aproximativ −2%: soldul crește, dar puterea de cumpărare scade. Este singura valoare care contează pentru decizii pe termen lung, iar randamentul nominal spune doar cum se schimbă numărul din cont.",
    vezi: ["inflatie", "putere-de-cumparare"],
  },
  {
    id: "dobanda-compusa",
    termen: "Dobândă compusă",
    termeni: ["dobândă compusă", "dobânda compusă", "capitalizare"],
    categorie: "Investiții",
    scurt: "Randamentul care se aplică și randamentului acumulat anterior.",
    lung: "Diferența față de dobânda simplă este că, la fiecare perioadă, câștigul se adaugă la capital și începe la rândul lui să producă. Efectul este aproape invizibil în primii ani și devine dominant după 15-20 de ani, motiv pentru care numărul de ani contează mai mult decât suma lunară.",
    vezi: ["randament-real", "cost-oportunitate"],
  },
  {
    id: "comision",
    termen: "Comision de administrare",
    termeni: ["comision de administrare", "comision"],
    categorie: "Investiții",
    scurt: "Procentul anual reținut de administratorul unui fond din valoarea investiției.",
    lung: "Se aplică întregii sume în fiecare an, inclusiv randamentului acumulat, exact ca dobânda compusă, dar în defavoarea ta. Diferența dintre 0,2% și 2% pe an poate consuma, pe 30 de ani, un sfert din câștigul final. Este singura variabilă din investiții care este cunoscută dinainte cu certitudine.",
    vezi: ["etf", "dae"],
  },
  {
    id: "lichiditate",
    termen: "Lichiditate",
    termeni: ["lichiditate", "lichid"],
    categorie: "Investiții",
    scurt: "Cât de repede poți transforma un activ în bani, fără să pierzi din valoare.",
    lung: "Banii din contul curent sunt perfect lichizi. Un ETF pe un indice mare se vinde în câteva secunde. Un apartament poate dura luni de zile și presupune costuri de tranzacție. Fondul de urgență trebuie ținut în active perfect lichide, tocmai pentru că nu știi dinainte când vei avea nevoie de el.",
    vezi: ["fond-de-urgenta"],
  },
  {
    id: "cost-oportunitate",
    termen: "Cost de oportunitate",
    termeni: ["cost de oportunitate", "costul de oportunitate"],
    categorie: "Investiții",
    scurt: "Valoarea alternativei la care renunți atunci când alegi ceva.",
    lung: "Fiecare leu cheltuit are două prețuri: cel de pe etichetă și cel al alternativei. O cheltuială de 5.000 lei costă, dacă alternativa era investirea pe 20 de ani la 7%, aproximativ 19.300 lei în bani viitori. Nu este un argument împotriva oricărei cheltuieli, ci o metodă de a vedea prețul întreg înainte de decizie.",
    vezi: ["dobanda-compusa"],
  },

  {
    id: "inflatie",
    termen: "Inflație",
    termeni: ["inflație", "inflația"],
    categorie: "Bazele",
    scurt: "Creșterea generală a prețurilor, care reduce puterea de cumpărare a banilor.",
    lung: "Nu îți ia bani din cont: suma rămâne identică. Se schimbă doar cât poți cumpăra cu ea. De aceea pierderea este greu de observat: nu apare nicio tranzacție. La 5% pe an, banii își pierd aproximativ 40% din putere în zece ani.",
    vezi: ["putere-de-cumparare", "randament-real"],
  },
  {
    id: "putere-de-cumparare",
    termen: "Putere de cumpărare",
    termeni: ["putere de cumpărare", "puterea de cumpărare"],
    categorie: "Bazele",
    scurt: "Cantitatea de bunuri și servicii pe care o poți cumpăra cu o sumă dată.",
    lung: "Este singura măsură care contează pe termen lung. O sumă exprimată „în puterea de cumpărare de azi” răspunde la întrebarea: cât ar valora acei bani viitori dacă i-ai avea acum? Fără această corecție, sumele proiectate pe 30 de ani par mult mai mari decât sunt.",
    vezi: ["inflatie", "randament-real"],
  },
  {
    id: "fond-de-urgenta",
    termen: "Fond de urgență",
    termeni: ["fond de urgență", "fondul de urgență"],
    categorie: "Bazele",
    scurt: "Rezervă lichidă care acoperă 3-6 luni de cheltuieli.",
    lung: "Nu este o investiție și nu trebuie să producă randament. Rolul lui este să existe atunci când ai nevoie, ca să nu fii forțat să te împrumuți scump sau să vinzi investiții exact în perioada în care valorează cel mai puțin. Se calculează la nivelul cheltuielilor, nu al venitului.",
    vezi: ["lichiditate", "inflatie"],
  },
  {
    id: "venit-net",
    termen: "Venit net",
    termeni: ["venit net", "salariu net"],
    categorie: "Bazele",
    scurt: "Suma care îți intră efectiv în cont, după contribuții și impozit.",
    lung: "Din salariul brut se rețin CAS (25%), CASS (10%) și impozitul pe venit (10%, aplicat pe ce rămâne după primele două și după deducerea personală). Angajatorul plătește în plus CAM, 2,25% peste brut. Între costul total al angajatorului și netul tău este o diferență de aproximativ 40%.",
    vezi: ["deducere-personala", "pilon-ii"],
  },
  {
    id: "deducere-personala",
    termen: "Deducere personală",
    termeni: ["deducere personală", "deducerea personală"],
    categorie: "Bazele",
    scurt: "Sumă scăzută din baza impozabilă, pentru salariile mici.",
    lung: "Se acordă integral până la nivelul salariului minim brut, scade treptat peste el și dispare complet la salariul minim plus 2.000 lei. Valoarea crește cu numărul de persoane aflate în întreținere. Este singurul element din formula salariului care depinde de situația ta personală.",
    vezi: ["venit-net"],
  },

  {
    id: "pilon-ii",
    termen: "Pilonul II",
    termeni: ["Pilonul II", "Pilon II", "pensie privată obligatorie"],
    categorie: "Pensii",
    scurt: "Pensia privată obligatorie: 4,75% din salariul brut, într-un cont pe numele tău.",
    lung: "Face parte din cei 25% CAS reținuți din salariu, dar spre deosebire de restul, această parte se acumulează într-un cont personal, administrat privat și investit. Banii sunt ai tăi și se moștenesc. Este obligatoriu pentru cei intrați în câmpul muncii după 2007.",
    vezi: ["pilon-i", "pilon-iii", "venit-net"],
  },
  {
    id: "pilon-i",
    termen: "Pilonul I",
    termeni: ["Pilonul I", "Pilon I", "pensie publică"],
    categorie: "Pensii",
    scurt: "Pensia publică, finanțată de contribuțiile generației active.",
    lung: "Nu este o acumulare: contribuțiile de azi plătesc pensiile de azi. Ce vei primi depinde de legislația din momentul pensionării și de raportul dintre numărul de salariați și cel de pensionari, factori pe care nu îi poți controla și care se deteriorează demografic.",
    vezi: ["pilon-ii"],
  },
  {
    id: "pilon-iii",
    termen: "Pilonul III",
    termeni: ["Pilonul III", "Pilon III", "pensie facultativă"],
    categorie: "Pensii",
    scurt: "Pensia privată facultativă, deductibilă fiscal până la 400 EUR pe an.",
    lung: "Contribuție voluntară, peste cea obligatorie. Deducerea fiscală înseamnă că statul îți returnează 10% din suma contribuită sub forma unui impozit mai mic, un câștig cert obținut înainte de orice randament al fondului. Peste plafonul de 400 EUR pe an, avantajul dispare și merită comparat cu un cont propriu de investiții.",
    vezi: ["pilon-ii", "comision"],
  },

  {
    id: "avalansa",
    termen: "Metoda avalanșă",
    termeni: ["avalanșă", "metoda avalanșă"],
    categorie: "Datorii",
    scurt: "Strategie de achitare care atacă întâi datoria cu dobânda cea mai mare.",
    lung: "Plătești minimul la toate datoriile și trimiți tot surplusul către cea mai scumpă. Este matematic optimă: minimizează dobânda totală plătită. Dezavantajul este psihologic: dacă datoria cea mai scumpă are și cel mai mare sold, prima victorie vine târziu.",
    vezi: ["bulgare"],
  },
  {
    id: "bulgare",
    termen: "Metoda bulgărelui de zăpadă",
    termeni: ["bulgăre de zăpadă", "metoda bulgărelui"],
    categorie: "Datorii",
    scurt: "Strategie care atacă întâi datoria cu soldul cel mai mic.",
    lung: "Costă puțin mai mult decât avalanșa, dar elimină rapid o datorie întreagă. Studiile de comportament arată că oamenii duc planul la capăt mai des atunci când văd victorii rapide, iar un plan dus la capăt bate un plan optim abandonat.",
    vezi: ["avalansa"],
  },
  {
    id: "refinantare",
    termen: "Refinanțare",
    termeni: ["refinanțare", "refinanța"],
    categorie: "Datorii",
    scurt: "Înlocuirea unui credit existent cu altul, în condiții mai bune.",
    lung: "Merită dacă noua dobândă este semnificativ mai mică și dacă economia depășește costurile de refinanțare: comisionul de rambursare anticipată la creditul vechi, taxele de analiză și eventualele costuri notariale la cel nou. Prelungirea perioadei reduce rata lunară, dar crește costul total.",
    vezi: ["dae", "grad-indatorare"],
  },
  {
    id: "pfa",
    termen: "PFA",
    termeni: ["PFA", "persoană fizică autorizată"],
    categorie: "Antreprenoriat",
    scurt: "Persoană fizică autorizată: cea mai simplă formă în care îți poți factura munca.",
    lung: "Se înființează repede și la cost mic, iar evidența contabilă este simplă. În sistem real, impozitarea pornește de la venitul net, adică încasări minus cheltuieli justificate cu documente. Diferența esențială față de un salariat: contribuțiile nu se calculează pe tot venitul, ci pe plafoane fixe legate de salariul minim, ceea ce face ca la venituri mari cota efectivă să scadă, dar și ca pensia acumulată să fie mai mică. Nu există concediu plătit, concediu medical decent sau protecție la pierderea clientului.",
    vezi: ["microintreprindere", "cheltuiala-deductibila", "pilon-ii"],
  },
  {
    id: "microintreprindere",
    termen: "Microîntreprindere",
    termeni: ["microîntreprindere", "impozit pe micro", "SRL micro"],
    categorie: "Antreprenoriat",
    scurt: "Regim fiscal în care firma plătește un impozit mic, dar aplicat pe venituri, nu pe profit.",
    lung: "Cota redusă induce în eroare: se aplică pe tot ce încasezi, indiferent de cheltuieli, deci o firmă cu marjă mică poate plăti mai mult decât ar plăti la impozit pe profit. Regimul are condiții: un plafon de venituri, cel puțin un salariat sau un administrator remunerat. La depășirea plafonului, firma trece la impozit pe profit. Banii ajung la asociat abia după al doilea impozit, cel pe dividende.",
    vezi: ["dividend", "pfa"],
  },
  {
    id: "dividend",
    termen: "Dividend",
    termeni: ["dividend", "dividende"],
    categorie: "Antreprenoriat",
    scurt: "Partea din profitul unei firme distribuită asociaților sau acționarilor.",
    lung: "Pentru un antreprenor, este a doua etapă a impozitării: firma plătește întâi impozitul pe venit sau pe profit, iar la scoaterea banilor se rețin impozitul pe dividende și, peste anumite praguri, CASS. Profitul din contul firmei nu este același lucru cu banii tăi. Pentru un investitor la bursă, dividendul este partea din randament plătită în numerar, spre deosebire de creșterea prețului acțiunii.",
    vezi: ["microintreprindere", "plafon-cass", "etf"],
  },
  {
    id: "plafon-cass",
    termen: "Plafon CASS",
    termeni: ["plafon CASS", "trepte CASS", "praguri de contribuție"],
    categorie: "Antreprenoriat",
    scurt: "Pragul de venit, exprimat în salarii minime, de la care se datorează contribuția la sănătate.",
    lung: "Pentru veniturile din afara salariului, CASS nu crește lin cu venitul: se calculează pe treapta în care te încadrezi. Un leu peste prag poate declanșa o contribuție pe un an întreg, deci intervalul din jurul pragului este singurul loc din sistemul fiscal unde a câștiga mai mult te poate lăsa cu mai puțin. Pragurile sunt exprimate în număr de salarii minime, deci se schimbă automat când se schimbă salariul minim.",
    vezi: ["pfa", "dividend"],
  },
  {
    id: "cheltuiala-deductibila",
    termen: "Cheltuială deductibilă",
    termeni: ["cheltuială deductibilă", "cheltuieli deductibile"],
    categorie: "Antreprenoriat",
    scurt: "Cheltuială legată de activitate, care scade venitul pe care se calculează taxele.",
    lung: "Deductibilitatea nu înseamnă că statul îți dă banii înapoi: o cheltuială de 1.000 de lei îți reduce impozitul cu aproximativ 100 de lei, nu cu 1.000. Rămâi deci în minus cu restul, de aceea nu are sens să cumperi ceva doar „ca să deduci”. Condiția este ca ea să servească activității și să fie justificată cu document. La o microîntreprindere, cheltuielile nu reduc impozitul pe venituri, ci doar profitul distribuibil.",
    vezi: ["pfa", "microintreprindere"],
  },
];
